# Generated by Django 4.2.4 on 2023-12-03 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_administrador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Administrador",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
