# Generated by Django 4.2.4 on 2023-12-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Peca",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantidade_em_estoque", models.IntegerField()),
            ],
        ),
    ]
