# Generated by Django 4.2.4 on 2023-12-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="descricao",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
