# Generated by Django 4.2.4 on 2023-12-04 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicos", "0003_remove_servico_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servico",
            name="peca",
        ),
    ]
