# Generated by Django 4.2.4 on 2023-12-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicos", "0004_remove_servico_peca"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="descricao",
            field=models.TextField(default=""),
        ),
    ]
