# Generated by Django 4.2.4 on 2023-12-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pecas", "0001_initial"),
        ("servicos", "0005_servico_descricao"),
        ("clientes", "0003_alter_carro_marca"),
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_total_pecas",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "valor_total_servico",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("problema_carro", models.TextField()),
                ("data_conclusao", models.DateTimeField()),
                ("concluida", models.BooleanField(default=False)),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clientes.carro"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funcionarios.equipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemServicoPeca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordem_servico.ordemservico",
                    ),
                ),
                (
                    "peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pecas.peca"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="pecas",
            field=models.ManyToManyField(
                through="ordem_servico.OrdemServicoPeca", to="pecas.peca"
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="servicos",
            field=models.ManyToManyField(to="servicos.servico"),
        ),
    ]
