# Generated by Django 4.2.4 on 2023-12-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordem_servico", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservicopeca",
            name="quantidade",
            field=models.IntegerField(null=True),
        ),
    ]
